# swiftlint 0.27.0

excluded:
  - Pods
  - AppName/Resources/Images/Images.swift
  - AppName/Resources/Localization/Localizable.swift
  - AppName/Application/CoreLayer/Common/Extensions/Container.swift
  - vendor

opt_in_rules:
#  - sorted_imports
#  - explicit_top_level_acl
#  - attributes
#  - explicit_enum_raw_value
#  - explicit_type_interface
#  - file_header
#  - no_grouping_extension
#  - prohibited_super_call
  - vertical_whitespace_closing_braces
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - object_literal
  - empty_count
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

type_name:
    min_length: 2
    max_length: 54

function_body_length: 50
line_length: 150
file_length: 700

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 34
    error: 34
  excluded:
    - initialViewControllersTypes
cyclomatic_complexity:
  error: 30

vertical_whitespace:
  max_empty_lines: 1
  severity: error
